/**
 * incidentReport.js
 * -----------------
 * Sequelize model for the `incidentReport` table.
 *
 * Central to the platform's reporting workflow. A survivor submits an
 * incident report that progresses through a 7-state lifecycle as NGO staff
 * review, support, investigate, and resolve it. Each report links to zero
 * or one legal case (auto-created on escalation) and zero or many evidence
 * files uploaded at submission time.
 *
 * Status state machine (see docs/reporting.md for full transition graph):
 *   SUBMITTED → UNDER_REVIEW → ACTIVE_SUPPORT → UNDER_INVESTIGATION
 *            → LEGAL_REVIEW → ESCALATED_TO_LEGAL_CASE
 *            → RESOLVED | WITHDRAWN
 *
 * Relationships defined in models/index.js:
 *   - incidentReport.belongsTo(survivorProfile)
 *   - incidentReport.hasMany(evidenceFile)
 *   - incidentReport.hasOne(legalCaseFile)
 */
 
const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');
 
const IncidentReport = sequelize.define('incidentReport', {
 
  reportId: {
    type:       DataTypes.STRING(36),
    primaryKey: true,
    allowNull:  false,
    comment:    'UUID primary key — generated by application before insert'
  },
 
  /**
   * The survivor who filed this report.
   * CASCADE delete: if a survivor account is deleted, their reports go too.
   */
  survivorId: {
    type:      DataTypes.STRING(36),
    allowNull: false,
    comment:   'FK to survivorProfile — the survivor who submitted this report'
  },
 
  /**
   * The GBV category of the incident — selected from a predefined list
   * designed to be survivor-friendly (see SSD §21.1).
   * Stored as VARCHAR rather than ENUM so that new categories can be
   * added without an ALTER TABLE migration.
   */
  incidentCategory: {
    type:      DataTypes.STRING(50),
    allowNull: false,
    comment:   'GBV incident category — e.g. physical_violence, sexual_violence'
  },
 
  /**
   * Severity of the incident — Low, Medium, High, or Critical.
   * Used by NGO staff to triage and prioritise response.
   */
  severityLevel: {
    type:      DataTypes.STRING(20),
    allowNull: false,
    comment:   'Triage severity — LOW | MEDIUM | HIGH | CRITICAL'
  },
 
  /**
   * Survivor's description of the incident.
   * TEXT allows for long-form narratives.
   */
  incidentDescriptionText: {
    type:      DataTypes.TEXT,
    allowNull: false,
    comment:   'Full survivor narrative of the incident'
  },
 
  /**
   * Location where the incident occurred.
   * Not the survivor's address — the incident location.
   */
  incidentLocation: {
    type:    DataTypes.STRING(100),
    comment: 'Location of the incident — not the survivor residence'
  },
 
  /**
   * Date the incident occurred — may differ from submission date.
   */
  incidentDate: {
    type:    DataTypes.DATEONLY,
    comment: 'Date the incident occurred — DATE only, no time component'
  },
 
  /**
   * Current status in the report lifecycle.
   * Valid transitions are defined in SSD §8.10.
   * Only NGO staff can advance most statuses; survivors can only WITHDRAW.
   */
  currentReportStatus: {
    type:      DataTypes.ENUM(
      'SUBMITTED',
      'UNDER_REVIEW',
      'ACTIVE_SUPPORT',
      'UNDER_INVESTIGATION',
      'LEGAL_REVIEW',
      'ESCALATED_TO_LEGAL_CASE',
      'IN_PROGRESS',
      'ESCALATED',
      'RESOLVED',
      'WITHDRAWN'
    ),
    allowNull: false,
    defaultValue: 'SUBMITTED',
    comment:   'Current position in the report lifecycle state machine'
  },
 
  reportCreationTimestamp: {
    type:         DataTypes.DATE,
    defaultValue: DataTypes.NOW,
    comment:      'UTC timestamp of when this report was first submitted'
  }
 
}, {
  tableName: 'incidentReport',
  comment:   'Core incident report — submitted by survivors, reviewed by NGO staff'
});

module.exports = IncidentReport;