const { DataTypes } = require('sequelize');
const { randomUUID } = require('crypto');
const sequelize = require('../config/database');

/**
 * staffReassignmentRequest
 * ------------------------
 * Survivor-initiated request record for changing assigned counsellor/legal counsel.
 *
 * Lifecycle:
 * - Created by survivor with requested scope + reason
 * - Reviewed by NGO admin (approved/rejected)
 * - May be cancelled by survivor before review
 *
 * Design notes:
 * - `requestedScope` allows partial reassignment (counsellor only, legal only, or both)
 * - `requestStatus` is the workflow gate used by controller logic
 * - `ngoAdminReviewerUserId` + `reviewTimestamp` provide accountability trail
 */
const StaffReassignmentRequest = sequelize.define('staffReassignmentRequest', {

  /** UUID primary key — generated by application via randomUUID() before insert. */
  requestId: {
    type:         DataTypes.STRING(36),
    primaryKey:   true,
    allowNull:    false,
    defaultValue: () => randomUUID(),
    comment:      'UUID primary key generated by the application'
  },

  /**
   * The survivor who submitted the request.
   * CASCADE: if the survivor account is removed, their requests are removed too.
   */
  survivorId: {
    type:      DataTypes.STRING(36),
    allowNull: false,
    comment:   'FK to survivorProfile — survivor who submitted the reassignment request'
  },

  /**
   * Which staff relationship(s) the survivor wants to change.
   * BOTH is the default — survivors can request a counsellor-only or
   * legal-counsel-only reassignment if needed.
   */
  requestedScope: {
    type:         DataTypes.ENUM('COUNSELLOR', 'LEGAL_COUNSEL', 'BOTH'),
    allowNull:    false,
    defaultValue: 'BOTH',
    comment:      'Which assignment(s) to reassign — COUNSELLOR | LEGAL_COUNSEL | BOTH'
  },

  /** Survivor's explanation for requesting the reassignment. */
  requestReasonText: {
    type:      DataTypes.TEXT,
    allowNull: false,
    comment:   'Survivor-provided reason for the reassignment request'
  },

  /**
   * Current workflow state of the request.
   * CANCELLED: survivor withdrew the request before NGO Admin reviewed it.
   */
  requestStatus: {
    type:         DataTypes.ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'),
    allowNull:    false,
    defaultValue: 'PENDING',
    comment:      'Workflow state — PENDING until NGO Admin acts or survivor cancels'
  },

  /**
   * The NGO Admin user who reviewed this request.
   * NULL on PENDING and CANCELLED requests.
   */
  ngoAdminReviewerUserId: {
    type:      DataTypes.STRING(36),
    allowNull: true,
    comment:   'FK to userAccount (NGO_ADMIN) — set when the request is reviewed'
  },

  /** Optional note from the reviewing NGO Admin explaining the decision. */
  ngoAdminReviewNote: {
    type:      DataTypes.TEXT,
    allowNull: true,
    comment:   'Optional NGO Admin note explaining the approval or rejection'
  },

  /** UTC timestamp of when the NGO Admin approved or rejected the request. */
  reviewTimestamp: {
    type:      DataTypes.DATE,
    allowNull: true,
    comment:   'UTC timestamp of NGO Admin review — NULL until reviewed'
  },

  /** UTC timestamp of when the survivor submitted the request. */
  requestTimestamp: {
    type:         DataTypes.DATE,
    allowNull:    false,
    defaultValue: DataTypes.NOW,
    comment:      'UTC timestamp of when the survivor submitted the request'
  }

}, {
  tableName: 'staffReassignmentRequest',
  comment:   'Survivor-initiated reassignment request — reviewed and actioned by NGO Admin'
});

module.exports = StaffReassignmentRequest;
