/**
 * userAccount.js
 * --------------
 * Sequelize model for the `userAccount` table.
 *
 * This is the base identity table for every user on the platform,
 * regardless of role. All role-specific profiles (survivorProfile,
 * counsellorProfile, etc.) reference this table via a foreign key on userId.
 *
 * Relationships defined in models/index.js:
 *   - userAccount.hasOne(survivorProfile)
 *   - userAccount.hasOne(counsellorProfile)
 *   - userAccount.hasOne(legalCounselProfile)
 *   - userAccount.hasOne(ngoAdministratorProfile)
 *   - userAccount.hasOne(systemAdministratorProfile)
 *   - userAccount.hasMany(inAppNotification)
 *   - userAccount.hasMany(directChatMessage)
 *   - userAccount.hasMany(communityMessage)
 *   - userAccount.hasMany(moderationActionLog) (as moderator)
 *   - userAccount.hasMany(moderationActionLog) (as target)
 *   - userAccount.hasMany(harmfulContentReport) (as reporter)
 *   - userAccount.hasMany(auditLog)
 *   - userAccount.hasMany(supportResource)
 */

const { DataTypes } = require('sequelize');
const { randomUUID } = require('crypto');
const sequelize = require('../config/database');

const UserAccount = sequelize.define('userAccount', {

  /**
   * Primary key — UUID string generated by the application layer
   * (or via crypto.randomUUID()) before insertion.
   * Using VARCHAR(36) UUIDs instead of AUTO_INCREMENT integers
   * prevents enumeration attacks on user IDs.
   */
  userId: {
    type:       DataTypes.STRING(36),
    primaryKey: true,
    allowNull:  false,
    defaultValue: () => randomUUID(),
    comment:    'UUID primary key — generated by application before insert'
  },

  /**
   * The user's phone number — used for OTP authentication and as
   * the login identifier. Must be unique across all accounts.
   * Stored without formatting (digits only where possible).
   */
  phoneNumber: {
    type:      DataTypes.STRING(15),
    allowNull: false,
    unique:    true,
    comment:   'Primary login identifier — must be unique across all users'
  },

  /**
   * Bcrypt-hashed password. Never stored as plaintext.
   * The application layer hashes the password before passing it here.
   */
  hashedPassword: {
    type:      DataTypes.STRING(255),
    allowNull: true,
    comment:   'Bcrypt hash of the user password — never stored as plaintext'
  },

  /**
   * Role determines which profile table the user has and what
   * permissions the RBAC middleware grants them.
   */
  userRole: {
    type:      DataTypes.ENUM('SURVIVOR', 'COUNSELLOR', 'LEGAL_COUNSEL', 'NGO_ADMIN', 'SYSTEM_ADMIN'),
    allowNull: false,
    defaultValue: 'SURVIVOR',
    comment:   'Role-based access control role — drives permissions across all modules'
  },

  /**
   * Compatibility role used by auth responses and existing frontend logic.
   * Mirrors userRole semantics in a lowercase/free-text form.
   */
  role: {
    type: DataTypes.STRING,
    defaultValue: 'survivor'
},

  /**
   * Compatibility status consumed by older auth/account flows.
   * accountStatus remains the authoritative RBAC/account lifecycle field.
   */
  status: {
    type: DataTypes.STRING,
    defaultValue: 'active'
},

  /**
   * Account status lifecycle.
   * - ACTIVE: normal access.
   * - SUSPENDED: temporary operational block (staff suspension, moderation hold).
   * - DEACTIVATED: soft-delete — data preserved for audit; account unreachable.
   * - BANNED: explicit NGO admin enforcement action for policy violations.
   *   Ban metadata (reason, expiry, actor) is stored in banReason / banExpiresAt /
   *   bannedAt / bannedByUserId fields below.
   *
   * IMPORTANT (MySQL ENUM): adding a new value to this ENUM via sequelize.sync
   * with alter:true can be unreliable. If the BANNED value does not appear after
   * sync, run: ALTER TABLE userAccount MODIFY accountStatus
   * ENUM('ACTIVE','SUSPENDED','DEACTIVATED','BANNED') NOT NULL DEFAULT 'ACTIVE';
   */
  accountStatus: {
    type:         DataTypes.ENUM('ACTIVE', 'SUSPENDED', 'DEACTIVATED', 'BANNED'),
    allowNull:    false,
    defaultValue: 'ACTIVE',
    comment:      'Controls whether the user can access the platform'
  },

  /**
   * Ban reason — human-readable justification entered by the NGO admin at ban time.
   * Required when accountStatus is set to BANNED; null otherwise.
   * Follows the discreet wording policy when surfaced to non-admin users.
   */
  banReason: {
    type:      DataTypes.TEXT,
    allowNull: true,
    comment:   'Mandatory reason entered by NGO admin when banning this account'
  },

  /**
   * UTC timestamp when this account was banned.
   * Set by the ban endpoint; cleared on unban.
   */
  bannedAt: {
    type:      DataTypes.DATE,
    allowNull: true,
    comment:   'UTC timestamp of when the ban was applied'
  },

  /**
   * Optional UTC expiry for temporary bans.
   * NULL means permanent — ban stands until an admin manually unbans.
   * When banExpiresAt is set to a past date and the user authenticates,
   * the system auto-restores accountStatus to ACTIVE and clears ban fields.
   */
  banExpiresAt: {
    type:      DataTypes.DATE,
    allowNull: true,
    comment:   'UTC expiry for temporary bans — null means permanent'
  },

  /**
   * userId of the NGO admin who issued the ban.
   * Stored for audit trail and ban-history display; not a FK association
   * to avoid circular cascade complexity.
   */
  bannedByUserId: {
    type:      DataTypes.STRING(36),
    allowNull: true,
    comment:   'userId of the NGO admin who applied the ban'
  },

  /**
   * Whether the user has successfully verified their phone number
   * via OTP. Accounts where this is FALSE cannot access full features.
   */
  isOtpVerified: {
    type:         DataTypes.BOOLEAN,
    defaultValue: false,
    comment:      'Set to TRUE only after successful OTP verification at registration'
  },

  /**
   * Account creation timestamp — set automatically at INSERT time.
   */
  accountCreationTimestamp: {
    type:         DataTypes.DATE,
    defaultValue: DataTypes.NOW,
    comment:      'UTC timestamp of when this account was first created'
  },

  otpHash: {
    type: DataTypes.STRING(255), // Must hold a 60-char bcrypt hash — STRING(10) truncated and broke all OTP paths
    allowNull: true,
    comment: 'Bcrypt hash of the active OTP (signup/signin/reset); never the plaintext code'
  },

  /**
   * Declares which workflow the current OTP belongs to.
   * This prevents reusing a signup OTP for signin/reset (or vice versa).
   */
  otpPurpose: {
    type: DataTypes.STRING(40),
    allowNull: true,
    comment: 'Purpose for current OTP (SIGNUP_OTP, SIGNIN_OTP, PASSWORD_RESET)'
  },

  /**
   * UTC expiry boundary for the active OTP.
   * Verification attempts after this timestamp are rejected.
   */
  otpExpiresAt: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Expiry timestamp for the active OTP code'
  },

  /**
   * Failed OTP verification attempts for the currently issued OTP.
   * Reset whenever a new OTP is issued.
   */
  otpAttemptCount: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    defaultValue: 0,
    comment: 'Failed OTP verification attempts for the active OTP code'
  },

  /**
   * Failed password-login attempts for lockout policy.
   * Cleared on successful password authentication.
   */
  authFailedAttempts: {
    type: DataTypes.INTEGER.UNSIGNED,
    allowNull: false,
    defaultValue: 0,
    comment: 'Consecutive failed password login attempts'
  },

  /**
   * Temporary lock timestamp after repeated auth failures.
   * Auth requests are blocked while now < authLockUntil.
   */
  authLockUntil: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Temporary account lock timestamp after repeated auth failures'
  }

}, {
  tableName: 'userAccount',
  comment:   'Base identity table — every platform user has exactly one row here'
});

module.exports = UserAccount;
