/**
 * userAccount.js
 * --------------
 * Sequelize model for the `userAccount` table.
 *
 * This is the base identity table for every user on the platform,
 * regardless of role. All role-specific profiles (survivorProfile,
 * counsellorProfile, etc.) reference this table via a foreign key on userId.
 *
 * Relationships defined in models/index.js:
 *   - userAccount.hasOne(survivorProfile)
 *   - userAccount.hasOne(counsellorProfile)
 *   - userAccount.hasOne(legalCounselProfile)
 *   - userAccount.hasOne(ngoAdministratorProfile)
 *   - userAccount.hasOne(systemAdministratorProfile)
 *   - userAccount.hasMany(inAppNotification)
 *   - userAccount.hasMany(directChatMessage)
 *   - userAccount.hasMany(communityMessage)
 *   - userAccount.hasMany(moderationActionLog) (as moderator)
 *   - userAccount.hasMany(moderationActionLog) (as target)
 *   - userAccount.hasMany(harmfulContentReport) (as reporter)
 *   - userAccount.hasMany(auditLog)
 *   - userAccount.hasMany(supportResource)
 */

const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const UserAccount = sequelize.define('userAccount', {

  /**
   * Primary key — UUID string generated by the application layer
   * (or via crypto.randomUUID()) before insertion.
   * Using VARCHAR(36) UUIDs instead of AUTO_INCREMENT integers
   * prevents enumeration attacks on user IDs.
   */
  userId: {
    type:       DataTypes.STRING(36),
    primaryKey: true,
    allowNull:  false,
    comment:    'UUID primary key — generated by application before insert'
  },

  /**
   * The user's phone number — used for OTP authentication and as
   * the login identifier. Must be unique across all accounts.
   * Stored without formatting (digits only where possible).
   */
  phoneNumber: {
    type:      DataTypes.STRING(15),
    allowNull: false,
    unique:    true,
    comment:   'Primary login identifier — must be unique across all users'
  },

  /**
   * Bcrypt-hashed password. Never stored as plaintext.
   * The application layer hashes the password before passing it here.
   */
  hashedPassword: {
    type:      DataTypes.STRING(255),
    allowNull: false,
    comment:   'Bcrypt hash of the user password — never stored as plaintext'
  },

  /**
   * Role determines which profile table the user has and what
   * permissions the RBAC middleware grants them.
   */
  userRole: {
    type:      DataTypes.ENUM('SURVIVOR', 'COUNSELLOR', 'LEGAL_COUNSEL', 'NGO_ADMIN', 'SYSTEM_ADMIN'),
    allowNull: false,
    comment:   'Role-based access control role — drives permissions across all modules'
  },

  /**
   * Account status — SUSPENDED accounts cannot log in.
   * DEACTIVATED accounts are soft-deleted (data preserved for audit).
   */
  accountStatus: {
    type:         DataTypes.ENUM('ACTIVE', 'SUSPENDED', 'DEACTIVATED'),
    allowNull:    false,
    defaultValue: 'ACTIVE',
    comment:      'Controls whether the user can access the platform'
  },

  /**
   * Whether the user has successfully verified their phone number
   * via OTP. Accounts where this is FALSE cannot access full features.
   */
  isOtpVerified: {
    type:         DataTypes.BOOLEAN,
    defaultValue: false,
    comment:      'Set to TRUE only after successful OTP verification at registration'
  },

  /**
   * Account creation timestamp — set automatically at INSERT time.
   */
  accountCreationTimestamp: {
    type:         DataTypes.DATE,
    defaultValue: DataTypes.NOW,
    comment:      'UTC timestamp of when this account was first created'
  }

}, {
  tableName: 'userAccount',
  comment:   'Base identity table — every platform user has exactly one row here'
});

module.exports = UserAccount;